using System.ComponentModel.DataAnnotations;

namespace Taskdeck.Application.Services;

public class JwtSettings
{
    /// <summary>
    /// Minimum JWT signing-key length in characters. A single, authoritative floor shared by
    /// <see cref="JwtSettingsValidator"/> (fail-fast at startup) and the authentication
    /// registration (fail-fast when wiring JwtBearer). HMAC-SHA256 needs a 256-bit (32-byte)
    /// key; 32 characters is the practical floor that keeps both checks consistent.
    /// </summary>
    public const int MinSecretKeyLength = 32;

    /// <summary>
    /// JWT signing key. Generated by FirstRunBootstrapper if not configured.
    /// Not marked [Required] because the bootstrapper populates it before validation runs.
    /// Validated by <see cref="JwtSettingsValidator"/> to ensure it is non-empty and at least
    /// <see cref="MinSecretKeyLength"/> characters at startup.
    /// </summary>
    public string SecretKey { get; set; } = string.Empty;

    [Required(AllowEmptyStrings = false)]
    public string Issuer { get; set; } = "Taskdeck";

    [Required(AllowEmptyStrings = false)]
    public string Audience { get; set; } = "TaskdeckUsers";

    [Range(1, 525600, ErrorMessage = "ExpirationMinutes must be between 1 and 525600 (1 year).")]
    public int ExpirationMinutes { get; set; } = 1440; // 24 hours
}
