using System.ComponentModel.DataAnnotations;

namespace Taskdeck.Application.Services;

public class JwtSettings
{
    /// <summary>
    /// JWT signing key. Generated by FirstRunBootstrapper if not configured.
    /// Not marked [Required] because the bootstrapper populates it before validation runs.
    /// Validated by <see cref="JwtSettingsValidator"/> to ensure it is non-empty at startup.
    /// </summary>
    public string SecretKey { get; set; } = string.Empty;

    [Required(AllowEmptyStrings = false)]
    public string Issuer { get; set; } = "Taskdeck";

    [Required(AllowEmptyStrings = false)]
    public string Audience { get; set; } = "TaskdeckUsers";

    [Range(1, 525600, ErrorMessage = "ExpirationMinutes must be between 1 and 525600 (1 year).")]
    public int ExpirationMinutes { get; set; } = 1440; // 24 hours
}
