import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { API_BASE_URL, registerAndAttachSession } from './support/authSession'
import { createBoardWithColumn } from './support/boardHelpers'
import { assertOk } from './support/httpAsserts'

test('personal plan persists, resumes focus and makes room without rescheduling a card', async ({ page, request }) => {
  const auth = await registerAndAttachSession(page, request, 'personal-plan')
  const headers = { Authorization: `Bearer ${auth.token}` }
  await page.addInitScript(() => {
    if (!localStorage.getItem('td.workspace.layout.v1')) localStorage.setItem('td.workspace.layout.v1', JSON.stringify({ experience: 'studio', presentation: 'studio' }))
    localStorage.setItem('td.paper.mode.v2', 'grove')
  })
  const boardId = await createBoardWithColumn(request, auth, String(Date.now()), { boardNamePrefix: 'Personal continuity', columnNamePrefix: 'Next' })
  const board = await (await request.get(`${API_BASE_URL}/boards/${boardId}`, { headers })).json()
  const response = await request.post(`${API_BASE_URL}/boards/${boardId}/cards`, { headers, data: { boardId, columnId: board.columns[0].id, title: 'One meaningful thread', dueDate: '2026-10-20T00:00:00Z' } })
  await assertOk(response, 'seed planned card')
  const card = await response.json()
  await page.goto('/workspace/plan')
  await expect(page.getByRole('heading', { name: 'Your personal plan', exact: true })).toBeVisible()
  await page.getByLabel('Project', { exact: true }).selectOption(boardId)
  await page.getByLabel('Card', { exact: true }).selectOption(card.id)
  await page.getByLabel('Plan for', { exact: true }).fill('2026-09-10')
  await page.getByRole('button', { name: 'Add to plan', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Added to your plan' })).toBeVisible()
  await page.reload()
  const entry = page.locator('article').filter({ has: page.getByRole('heading', { name: 'One meaningful thread' }) })
  await expect(entry).toContainText('2026-09-10')
  await page.getByRole('button', { name: 'Horizon', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026-09-10', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Board', exact: true }).click()
  await expect(entry).toContainText(board.name)
  await entry.getByRole('button', { name: 'Focus', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/cards/${card.id}/thinking\\?focus=1`))
  await expect(page.getByText('FOCUS · One thread at a time.')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Studio navigation' })).toBeHidden()
  await expect(page.getByRole('combobox', { name: 'Workspace experience' })).toBeHidden()
  await page.getByRole('button', { name: '+ thread', exact: true }).click()
  await page.getByLabel('Layer 1 details', { exact: true }).fill('Next time: check the unresolved edge case.')
  await page.getByRole('button', { name: 'Save thinking', exact: true }).click()
  await expect(page.getByText('Thinking saved', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/personal-focus-desktop.png', fullPage: true })
  await page.goto('/workspace/home')
  await expect(page.getByRole('region', { name: 'Personal continuity' })).toContainText('One meaningful thread')
  await expect(page.getByRole('list', { name: 'Your chosen threads' })).toContainText('One meaningful thread')
  await page.screenshot({ path: 'test-results/personal-home-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Resume focus', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/cards/${card.id}/thinking\\?focus=1`))
  await expect(page.getByLabel('Layer 1 details', { exact: true })).toHaveValue('Next time: check the unresolved edge case.')
  await page.getByRole('link', { name: 'Return to your plan', exact: true }).click()
  await entry.getByRole('button', { name: 'Plan tomorrow', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Planned for tomorrow' })).toBeVisible()
  const planned = await (await request.get(`${API_BASE_URL}/workspace/plan`, { headers })).json()
  expect(planned.entries).toHaveLength(1)
  expect(planned.lastWorked.cardId).toBe(card.id)
  for (const experience of ['classic', 'companion', 'unified', 'studio']) {
    await page.getByRole('combobox', { name: 'Workspace experience' }).selectOption(experience)
    await expect(entry).toBeVisible()
  }
  await page.setViewportSize({ width: 375, height: 812 })
  await page.screenshot({ path: 'test-results/personal-plan-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const accessibility = await new AxeBuilder({ page }).include('.personal-plan').analyze()
  expect(accessibility.violations).toEqual([])
  await entry.getByRole('button', { name: 'Make room', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Removed from your plan' })).toBeVisible()
  await expect(entry).toHaveCount(0)
  const currentCards = await (await request.get(`${API_BASE_URL}/boards/${boardId}/cards`, { headers })).json()
  expect(currentCards.find((item: { id: string }) => item.id === card.id)).toEqual(card)
})
