import { expect, test, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { API_BASE_URL, registerAndAttachSession } from './support/authSession'
import { createBoardWithColumn } from './support/boardHelpers'

const incompleteBoardReads = new WeakMap<Page, string[]>()
test.beforeEach(async ({ page }) => {
  const requests: string[] = []; incompleteBoardReads.set(page, requests)
  page.on('request', request => {
    const path = new URL(request.url()).pathname
    if (path === '/api/boards/' || path.startsWith('/api/boards//')) requests.push(path)
  })
})
test.afterEach(async ({ page }) => { expect(incompleteBoardReads.get(page)).toEqual([]) })
import { assertOk } from './support/httpAsserts'

test.use({ timezoneId: 'America/Los_Angeles', locale: 'en-US' })

test('uncertain plan writes hide cached entries until explicit refresh reconciles the server', async ({ page, request }) => {
  const auth = await registerAndAttachSession(page, request, 'plan-recovery')
  const headers = { Authorization: `Bearer ${auth.token}` }
  const boardId = await createBoardWithColumn(request, auth, String(Date.now()), { boardNamePrefix: 'Plan recovery', columnNamePrefix: 'Next', description: 'Synthetic recovery proof' })
  const board = await (await request.get(`${API_BASE_URL}/boards/${boardId}`, { headers })).json()
  const response = await request.post(`${API_BASE_URL}/boards/${boardId}/cards`, { headers, data: { boardId, columnId: board.columns[0].id, title: 'Recover this private thread' } })
  await assertOk(response, 'seed recovery card')
  const card = await response.json()
  await assertOk(await request.put(`${API_BASE_URL}/workspace/plan`, { headers, data: { expectedRevision: 0, entries: [{ boardId, cardId: card.id, plannedDate: '2026-09-10' }] } }), 'seed recovery plan')
  await page.goto('/workspace/plan')
  const entry = page.locator('article').filter({ has: page.getByRole('heading', { name: card.title }) })
  await expect(entry).toBeVisible()
  await page.route('**/api/workspace/plan/focus', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ errorCode: 'UnexpectedError', message: 'Synthetic uncertain response' }) }))
  await entry.getByRole('button', { name: 'Focus', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/cards/${card.id}/thinking\\?focus=1`))
  await expect(page.getByRole('alert')).toContainText('Focus could not be confirmed.')
  await page.unroute('**/api/workspace/plan/focus')
  await page.getByRole('link', { name: 'Refresh personal plan', exact: true }).click()
  await expect(entry).toBeVisible()
  let writes = 0
  await page.route('**/api/workspace/plan', async route => {
    if (route.request().method() !== 'PUT') return route.continue()
    writes++
    const committed = await route.fetch()
    expect(committed.ok()).toBe(true)
    await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ errorCode: 'UnexpectedError', message: 'Synthetic response lost after commit' }) })
  })
  await entry.getByRole('button', { name: 'Make room', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Plan change could not be confirmed.')
  await expect(entry).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Add to plan', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Refresh personal plan', exact: true }).click()
  await expect(page.getByText('Your plan has room. Choose a card above, then focus on one thread at a time.')).toBeVisible()
  const saved = await (await request.get(`${API_BASE_URL}/workspace/plan`, { headers })).json()
  expect(saved.entries).toEqual([])
  expect(saved.revision).toBe(2)
  expect(saved.lastWorked).toBeNull()
  expect(writes).toBe(1)
})

test('personal plan persists, resumes focus and makes room without rescheduling a card', async ({ page, request }) => {
  const auth = await registerAndAttachSession(page, request, 'personal-plan')
  const headers = { Authorization: `Bearer ${auth.token}` }
  await page.addInitScript(() => {
    if (!localStorage.getItem('td.workspace.layout.v1')) localStorage.setItem('td.workspace.layout.v1', JSON.stringify({ experience: 'studio', presentation: 'studio' }))
    if (!localStorage.getItem('td.paper.mode.v2')) localStorage.setItem('td.paper.mode.v2', 'grove')
  })
  const boardId = await createBoardWithColumn(request, auth, String(Date.now()), { boardNamePrefix: 'Personal continuity', columnNamePrefix: 'Next' })
  const board = await (await request.get(`${API_BASE_URL}/boards/${boardId}`, { headers })).json()
  const response = await request.post(`${API_BASE_URL}/boards/${boardId}/cards`, { headers, data: { boardId, columnId: board.columns[0].id, title: 'One meaningful thread', dueDate: '2026-10-20T00:00:00Z' } })
  await assertOk(response, 'seed planned card')
  const card = await response.json()
  await page.goto('/workspace/plan')
  await expect(page.getByRole('heading', { name: 'Your personal plan', exact: true })).toBeVisible()
  await page.getByLabel('Project', { exact: true }).selectOption(boardId)
  await page.getByLabel('Card', { exact: true }).selectOption(card.id)
  await page.getByLabel('Plan for', { exact: true }).fill('2026-09-10')
  await page.getByRole('button', { name: 'Add to plan', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Added to your plan' })).toBeVisible()
  await page.reload()
  const entry = page.locator('article').filter({ has: page.getByRole('heading', { name: 'One meaningful thread' }) })
  await expect(entry).toContainText('2026-09-10')
  await expect(entry).toContainText('Card due 10/20/2026')
  await page.locator('.personal-plan').getByRole('button', { name: 'Today', exact: true }).click()
  const today = await page.evaluate(() => {
    const now = new Date()
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
  })
  await expect(page.getByLabel('Show planned date', { exact: true })).toHaveValue(today)
  await page.getByRole('button', { name: 'All dates', exact: true }).click()
  await page.getByRole('button', { name: 'Horizon', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026-09-10', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Board', exact: true }).click()
  await expect(entry).toContainText(board.name)
  await entry.getByRole('button', { name: 'Focus', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/cards/${card.id}/thinking\\?focus=1`))
  await expect(page.getByText('FOCUS · One thread at a time.')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Studio navigation' })).toBeHidden()
  await expect(page.getByRole('combobox', { name: 'Workspace experience' })).toBeHidden()
  await page.getByRole('button', { name: '+ thread', exact: true }).click()
  await page.getByLabel('Layer 1 details', { exact: true }).fill('Next time: check the unresolved edge case.')
  await page.getByRole('button', { name: 'Save thinking', exact: true }).click()
  await expect(page.getByText('Thinking saved', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/personal-focus-desktop.png', fullPage: true })
  await page.goto('/workspace/home')
  await expect(page.getByRole('region', { name: 'Personal continuity' })).toContainText('One meaningful thread')
  await expect(page.getByRole('list', { name: 'Your chosen threads' })).toContainText('One meaningful thread')
  await page.screenshot({ path: 'test-results/personal-home-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Resume focus', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/cards/${card.id}/thinking\\?focus=1`))
  await expect(page.getByLabel('Layer 1 details', { exact: true })).toHaveValue('Next time: check the unresolved edge case.')
  await page.goto('/workspace/home')
  await page.getByRole('combobox', { name: 'Workspace experience' }).selectOption('classic')
  for (const mode of ['grove', 'off']) {
    await page.evaluate(value => localStorage.setItem('td.paper.mode.v2', value), mode)
    await page.reload()
    const continuity = page.getByRole('region', { name: 'Personal continuity' })
    await expect(continuity).toContainText('One meaningful thread')
    await expect(continuity.getByRole('button', { name: 'Resume focus', exact: true })).toBeEnabled()
    await continuity.getByRole('button', { name: 'Resume focus', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/cards/${card.id}/thinking\\?focus=1`))
    await expect(page.getByLabel('Layer 1 details', { exact: true })).toHaveValue('Next time: check the unresolved edge case.')
    await page.goto('/workspace/home')
  }
  await page.goto('/workspace/plan')
  await entry.getByRole('button', { name: 'Plan tomorrow', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Planned for tomorrow' })).toBeVisible()
  const planned = await (await request.get(`${API_BASE_URL}/workspace/plan`, { headers })).json()
  expect(planned.entries).toHaveLength(1)
  expect(planned.lastWorked.cardId).toBe(card.id)
  for (const experience of ['classic', 'companion', 'unified', 'studio']) {
    await page.getByRole('combobox', { name: 'Workspace experience' }).selectOption(experience)
    await expect(entry).toBeVisible()
  }
  await page.setViewportSize({ width: 375, height: 812 })
  await page.screenshot({ path: 'test-results/personal-plan-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const accessibility = await new AxeBuilder({ page }).include('.personal-plan').analyze()
  expect(accessibility.violations).toEqual([])
  await entry.getByRole('button', { name: 'Make room', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Removed from your plan' })).toBeVisible()
  await expect(entry).toHaveCount(0)
  const currentCards = await (await request.get(`${API_BASE_URL}/boards/${boardId}/cards`, { headers })).json()
  expect(currentCards.find((item: { id: string }) => item.id === card.id)).toEqual(card)
})
